index:
    path:       /
    defaults:   { _controller: app.index_controller:indexAction }
    methods:    [GET]

api_filters:
    path:       /server-information/get-filter-options
    defaults:   { _controller: app.filter_controller:customerDataFiltersAction }
    methods:    [GET]

api_search:
    path:       /server-information/search-by-resource
    defaults:   { _controller: app.search_controller:searchAction }
    methods:    [GET]